# Generated by Django 3.2.4 on 2021-06-17 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hub', '0002_instructor_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='users',
            field=models.ManyToManyField(related_name='colleges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='users',
            field=models.ManyToManyField(related_name='departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instructor',
            name='facultyPage',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='major',
            name='users',
            field=models.ManyToManyField(related_name='majors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('instructor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hub.instructor')),
                ('students', models.ManyToManyField(related_name='courses', to='hub.Student')),
            ],
        ),
    ]
