# Generated by Django 3.2.4 on 2021-06-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0009_alter_course_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='facultyPage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
