# Generated by Django 3.2.4 on 2021-06-18 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hub', '0015_projectproposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField()),
                ('complete', models.BooleanField(default=False)),
                ('interestedUsers', models.ManyToManyField(blank=True, related_name='interested_users', to=settings.AUTH_USER_MODEL)),
                ('owningGroup', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hub.group')),
                ('owningUser', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('relatedProposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hub.projectproposal')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('note', models.JSONField()),
                ('created', models.DateTimeField()),
                ('relatedProject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.project')),
            ],
        ),
    ]
