# Generated by Django 3.2.4 on 2021-06-18 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hub', '0020_auto_20210618_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='groupTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_to', to='hub.group'),
        ),
        migrations.AlterField(
            model_name='message',
            name='userTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
