# Generated by Django 3.2.4 on 2021-07-06 03:49

from django.db import migrations, models
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0025_project_description'),
    ]

    operations = [
        TrigramExtension(),
    ]
