# Generated by Django 3.2.4 on 2021-07-15 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hub', '0027_auto_20210712_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='owner',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owning_groups', to='auth.user'),
            preserve_default=False,
        ),
    ]
